;;; suwi-themes-common.el --- Shared palette and faces for Suwi themes -*- lexical-binding:t -*-

;; Copyright (C) 2025  Carl Steib

;;; Commentary:
;;
;; Shared palette semantics and common custom faces layered into every
;; Suwi theme family.

;;; Code:

(require 'modus-themes)

(defconst suwi-common-palette
  '(
    ;; Shared three-color rotation for headings and title-like text.
    (fg-heading-0 suwi-primary)
    (fg-heading-1 suwi-secondary)
    (fg-heading-2 suwi-tertiary)
    (fg-heading-3 suwi-primary)
    (fg-heading-4 suwi-secondary)
    (fg-heading-5 suwi-tertiary)
    (fg-heading-6 suwi-primary)
    (fg-heading-7 suwi-secondary)
    (fg-heading-8 suwi-tertiary)
    ;; Shared three-color rotation for completion matches.
    (fg-completion-match-0 suwi-primary)
    (fg-completion-match-1 suwi-secondary)
    (fg-completion-match-2 suwi-tertiary)
    (fg-completion-match-3 suwi-primary)
    ;; Rainbow delimiters cycle through the three semantic accents.
    (rainbow-0 fg-main)
    (rainbow-1 suwi-primary)
    (rainbow-2 suwi-secondary)
    (rainbow-3 suwi-tertiary)
    (rainbow-4 suwi-primary)
    (rainbow-5 suwi-secondary)
    (rainbow-6 suwi-tertiary)
    (rainbow-7 suwi-primary)
    (rainbow-8 suwi-secondary)
    ;; Used in tty, symbol-overlay, pulse, popup, pdf-tools, minimap, and others.
    (bg-red-intense bg-red)
    (bg-green-intense bg-green)
    (bg-yellow-intense bg-yellow)
    (bg-blue-intense bg-blue)
    (bg-magenta-intense bg-magenta)
    (bg-cyan-intense bg-cyan)
    ;; Used in tuareg, golden-ratio-scroll-screen, annotate.
    (bg-red-subtle bg-red)
    (bg-green-subtle bg-green)
    (bg-yellow-subtle bg-yellow)
    (bg-blue-subtle bg-blue)
    (bg-magenta-subtle bg-magenta)
    (bg-cyan-subtle bg-cyan)
    ;; These nuanced colors are not used directly in any faces.
    (bg-red-nuanced bg-red)
    (bg-green-nuanced bg-green)
    (bg-yellow-nuanced bg-yellow)
    (bg-blue-nuanced bg-blue)
    (bg-magenta-nuanced bg-magenta)
    (bg-cyan-nuanced bg-cyan)
    ;; Graph Colors
    (red-graph-0-bg red)
    (red-graph-1-bg red-faint)
    (green-graph-0-bg green)
    (green-graph-1-bg green-faint)
    (yellow-graph-0-bg yellow)
    (yellow-graph-1-bg yellow-faint)
    (blue-graph-0-bg blue)
    (blue-graph-1-bg blue-faint)
    (magenta-graph-0-bg magenta)
    (magenta-graph-1-bg magenta-faint)
    (cyan-graph-0-bg cyan)
    (cyan-graph-1-bg cyan-faint)
    (bg-graph-red-0 red-graph-0-bg)
    (bg-graph-red-1 red-graph-1-bg)
    (bg-graph-green-0 green-graph-0-bg)
    (bg-graph-green-1 green-graph-1-bg)
    (bg-graph-yellow-0 yellow-graph-0-bg)
    (bg-graph-yellow-1 yellow-graph-1-bg)
    (bg-graph-blue-0 blue-graph-0-bg)
    (bg-graph-blue-1 blue-graph-1-bg)
    (bg-graph-magenta-0 magenta-graph-0-bg)
    (bg-graph-magenta-1 magenta-graph-1-bg)
    (bg-graph-cyan-0 cyan-graph-0-bg)
    (bg-graph-cyan-1 cyan-graph-1-bg)
    ;; Rare colors
    (bg-clay bg-red-subtle)
    (fg-clay red)
    (bg-ochre bg-yellow-subtle)
    (fg-ochre yellow)
    (bg-lavender bg-magenta-subtle)
    (fg-lavender magenta)
    (bg-sage bg-green-subtle)
    (fg-sage green)
    (rust red-faint)
    (gold yellow)
    (olive green-faint)
    (slate blue)
    (indigo blue-faint)
    (maroon magenta-faint)
    (pink magenta)
    ;; Core neutral and greyscale remappings.
    (fringe bg-main)
    (bg-hl-line bg-dim)
    (bg-completion bg-hl-line)
    (bg-region bg-inactive)
    (fg-region fg-main)
    (fg-alt fg-main)
    (fg-main suwi-fg)
    (bg-tab-bar bg-dim)
    (bg-tab-current bg-main)
    (bg-tab-other bg-tab-bar)
    (bg-mode-line-active bg-dim)
    (fg-mode-line-active fg-main)
    (border-mode-line-active bg-mode-line-active)
    (bg-mode-line-inactive bg-main)
    (fg-mode-line-inactive fg-dim)
    (border-mode-line-inactive border)
    ;; Semantic code mappings.
    (comment fg-dim)
    (docstring comment)
    (string suwi-tertiary)
    (keyword suwi-keyword)
    (constant suwi-primary)
    (fnname suwi-secondary)
    (property suwi-secondary)
    (builtin suwi-primary)
    (fnname-call fg-main)
    (preprocessor fg-main)
    (rx-backslash fg-main)
    (rx-construct fg-main)
    (type suwi-primary)
    (variable suwi-secondary)
    (variable-use fg-main)
    ;; General semantic mappings.
    (cursor suwi-tertiary)
    (keybind suwi-primary)
    (name suwi-primary)
    (identifier suwi-tertiary)
    ;; Error, warning, and informational mappings.
    (err red)
    (warning yellow-warmer)
    (info cyan-warmer)
    (red-intense red)
    (green-intense green)
    (yellow-intense yellow)
    (blue-intense blue)
    (magenta-intense magenta)
    (cyan-intense cyan)
    (modeline-err err)
    (modeline-warning warning)
    (modeline-info info)
    (underline-err err)
    (underline-warning warning)
    (underline-note info)
    (bg-prominent-err bg-red-intense)
    (fg-prominent-err fg-main)
    (bg-prominent-warning bg-yellow-intense)
    (fg-prominent-warning fg-main)
    (bg-prominent-note bg-cyan-intense)
    (fg-prominent-note fg-main)
    (bg-active-argument bg-yellow-nuanced)
    (fg-active-argument yellow-warmer)
    (bg-active-value bg-cyan-nuanced)
    (fg-active-value cyan-warmer)
    ;; Date mappings.
    (date-common suwi-secondary)
    (date-deadline err)
    (date-deadline-subtle err)
    (date-event fg-alt)
    (date-holiday suwi-tertiary)
    (date-holiday-other suwi-tertiary)
    (date-range fg-alt)
    (date-scheduled suwi-secondary)
    (date-scheduled-subtle suwi-secondary)
    (date-weekday suwi-secondary)
    (date-weekend suwi-tertiary)
    ;; Theme-facing semantic colors.
    (suwi-primary blue-cooler)
    (suwi-secondary cyan)
    (suwi-tertiary magenta)
    (suwi-keyword suwi-fg)
    ;; Compatibility mappings for Modus accent slots.
    (accent-0 suwi-primary)
    (accent-1 suwi-primary)
    (accent-2 suwi-secondary)
    (accent-3 suwi-tertiary)
    ;; Special purpose
    (bg-hover bg-cyan)
    (bg-hover-secondary bg-yellow)
    (bg-diff-context bg-dim)
    ;; Paren match
    (bg-paren-match cyan-faint)
    (bg-paren-expression bg-cyan)
    (underline-paren-match unspecified)
    ;; Link mappings
    (fg-link blue-warmer)
    (underline-link blue-warmer)
    (fg-link-symbolic cyan)
    (underline-link-symbolic cyan)
    (fg-link-visited magenta)
    (underline-link-visited magenta)
    ;; Mail mappings
    (mail-cite-0 blue-faint)
    (mail-cite-1 yellow-warmer)
    (mail-cite-2 cyan-cooler)
    (mail-cite-3 red-cooler)
    (mail-part cyan)
    (mail-recipient magenta-cooler)
    (mail-subject magenta-warmer)
    (mail-other magenta-faint)
    ;; Mark mappings
    (bg-mark-delete bg-red-subtle)
    (fg-mark-delete red)
    (bg-mark-select bg-cyan-subtle)
    (fg-mark-select cyan)
    (bg-mark-other bg-yellow-subtle)
    (fg-mark-other yellow)
    ;; Prompt mappings
    (fg-prompt suwi-primary)
    ;; Prose mappings
    (fg-prose-code suwi-primary)
    (fg-prose-macro suwi-secondary)
    (fg-prose-verbatim suwi-tertiary)
    (prose-done green)
    (prose-todo red)
    (prose-metadata fg-dim)
    (prose-metadata-value fg-alt)
    (prose-table fg-alt)
    (prose-table-formula suwi-tertiary)
    (prose-tag suwi-tertiary)
    ;; Search mappings
    (bg-search-current bg-yellow-intense)
    (bg-search-lazy bg-cyan-intense)
    (bg-search-static bg-magenta-subtle)
    (bg-search-replace bg-red-intense)
    (bg-search-rx-group-0 bg-blue-intense)
    (bg-search-rx-group-1 bg-green-intense)
    (bg-search-rx-group-2 bg-red-subtle)
    (bg-search-rx-group-3 bg-magenta-subtle)
    (fg-button-active fg-main)
    (fg-button-inactive fg-dim)
    (bg-button-active bg-active)
    (bg-button-inactive bg-dim)
    (bracket fg-main)
    (delimiter fg-main)
    (docmarkup magenta-faint)
    (number fg-main)
    (operator fg-main)
    (punctuation fg-main)
    (bg-completion-match-0 unspecified)
    (bg-completion-match-1 unspecified)
    (bg-completion-match-2 unspecified)
    (bg-completion-match-3 unspecified)
    (date-now fg-main)
    (fg-line-number-inactive fg-dim)
    (fg-line-number-active fg-main)
    (bg-line-number-inactive bg-dim)
    (bg-line-number-active bg-active)
    (bg-link unspecified)
    (bg-link-symbolic unspecified)
    (bg-link-visited unspecified)
    (fg-paren-match fg-main)
    (bg-prompt unspecified)
    (bg-prose-block-delimiter bg-dim)
    (fg-prose-block-delimiter fg-dim)
    (bg-prose-block-contents bg-dim)
    (bg-prose-code unspecified)
    (bg-prose-macro unspecified)
    (bg-prose-verbatim unspecified)
    (fg-search-current yellow-warmer)
    (fg-search-lazy magenta-cooler)
    (fg-search-static fg-main)
    (fg-search-replace red-cooler)
    (fg-search-rx-group-0 blue-warmer)
    (fg-search-rx-group-1 green-warmer)
    (fg-search-rx-group-2 red-cooler)
    (fg-search-rx-group-3 magenta-cooler)
    (bg-space unspecified)
    (fg-space border)
    (bg-space-err bg-red-intense)
    (bg-term-black bg-main)
    (fg-term-black fg-main)
    (bg-term-black-bright bg-active)
    (fg-term-black-bright fg-dim)
    (bg-term-red red)
    (fg-term-red red)
    (bg-term-red-bright red-warmer)
    (fg-term-red-bright red-warmer)
    (bg-term-green green)
    (fg-term-green green)
    (bg-term-green-bright green-cooler)
    (fg-term-green-bright green-cooler)
    (bg-term-yellow yellow)
    (fg-term-yellow yellow)
    (bg-term-yellow-bright yellow-warmer)
    (fg-term-yellow-bright yellow-warmer)
    (bg-term-blue blue)
    (fg-term-blue blue)
    (bg-term-blue-bright blue-warmer)
    (fg-term-blue-bright blue-warmer)
    (bg-term-magenta magenta)
    (fg-term-magenta magenta)
    (bg-term-magenta-bright magenta-cooler)
    (fg-term-magenta-bright magenta-cooler)
    (bg-term-cyan cyan)
    (fg-term-cyan cyan)
    (bg-term-cyan-bright cyan-cooler)
    (fg-term-cyan-bright cyan-cooler)
    (bg-term-white bg-active)
    (fg-term-white bg-active)
    (bg-term-white-bright bg-main)
    (fg-term-white-bright bg-main)
    (bg-heading-0 unspecified)
    (bg-heading-1 unspecified)
    (bg-heading-2 unspecified)
    (bg-heading-3 unspecified)
    (bg-heading-4 unspecified)
    (bg-heading-5 unspecified)
    (bg-heading-6 unspecified)
    (bg-heading-7 unspecified)
    (bg-heading-8 unspecified)
    (overline-heading-0 unspecified)
    (overline-heading-1 unspecified)
    (overline-heading-2 unspecified)
    (overline-heading-3 unspecified)
    (overline-heading-4 unspecified)
    (overline-heading-5 unspecified)
    (overline-heading-6 unspecified)
    (overline-heading-7 unspecified)
    (overline-heading-8 unspecified))
  "Common palette shared by every Suwi theme, layered on a Modus palette.")

(defconst suwi-common-custom-faces
  '(
    `(mode-line
      ((,c :inherit modus-themes-ui-variable-pitch
           :background ,bg-mode-line-active
           :foreground ,fg-mode-line-active
           :box (:line-width -1 :color ,border-mode-line-active))))
    `(mode-line-active
      ((,c :inherit mode-line
           :box (:line-width -1 :color ,border-mode-line-active))))
    `(mode-line-inactive
      ((,c :inherit modus-themes-ui-variable-pitch
           :background ,bg-mode-line-inactive
           :foreground ,fg-mode-line-inactive
           :box (:line-width -1 :color ,border-mode-line-inactive))))
    `(hl-todo ((,c :foreground ,prose-todo)))
    `(show-paren-match ((,c :background ,bg-paren-match :foreground ,fg-main :weight bold)))
    `(diff-hl-insert ((,c :background ,bg-added :foreground ,fg-added)))
    `(diff-hl-delete ((,c :background ,bg-removed :foreground ,fg-removed)))
    `(diff-hl-change ((,c :background ,bg-changed :foreground ,fg-changed)))
    `(corfu-default ((,c :inherit modus-themes-fixed-pitch :background ,bg-main)))
    `(markdown-gfm-checkbox-face ((,c :foreground ,suwi-secondary)))
    `(magit-diff-file-heading ((,c :inherit modus-themes-bold :foreground ,suwi-secondary)))
    `(magit-diff-file-heading-highlight ((,c :inherit modus-themes-bold :background ,bg-dim :foreground ,suwi-secondary)))
    `(magit-branch-remote ((,c :foreground ,suwi-secondary)))
    `(magit-reflog-remote ((,c :inherit modus-themes-bold :foreground ,suwi-secondary)))
    `(git-commit-comment-branch-remote ((,c :inherit modus-themes-slant :foreground ,suwi-secondary)))
    `(magit-diff-hunk-heading ((,c :foreground ,fg-dim :background ,bg-main :box (:line-width -1 :color ,border-mode-line-inactive))))
    `(magit-diff-hunk-heading-highlight ((,c :inherit modus-themes-bold :foreground ,fg-main :background ,bg-dim)))
    `(magit-diff-added ((,c :background ,bg-added-faint :foreground ,fg-dim)))
    `(magit-diff-removed ((,c :background ,bg-removed-faint :foreground ,fg-dim))))
  "Common custom faces for all Suwi themes on top of `modus-themes-faces'.")

(provide 'suwi-themes-common)

;;; suwi-themes-common.el ends here
